services:
  traefik:
    image: ${TRAEFIK_IMAGE:-traefik:v2.11}
    restart: always
    network_mode: host
    volumes:
      - ./data/traefik/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./data/traefik/dynamic:/etc/traefik/dynamic:ro
      - ./data/letsencrypt:/letsencrypt
      - ./data/log:/var/log/traefik
      - ./.htpasswd:/etc/traefik/.htpasswd:ro
    environment:
      TZ: "${TZ:-Asia/Tokyo}"
