#SSL設定用のサンプル
server {
  listen	80 default;
  listen	[::]:80;
  server_name ${DOMAIN};
  location ^~ /.well-known {
    root /usr/share/nginx/html;
  }
  
  location / {
    return 301 https://$host$request_uri;
#    root /usr/share/nginx/html;
  }
}

