server {
    listen 80;
    listen [::]:80;
    server_name ${MIRAKURUN_HOST};

    location ^~ /.well-known/ {
        root /usr/share/nginx/html;
        try_files $uri =404;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}
