server {
    listen 80;
    listen [::]:80;
    server_name ${MIRAKURUN_HOST};

    location ^~ /.well-known/ {
        root /usr/share/nginx/html;
        try_files $uri =404;
    }

    location / {
        proxy_pass http://${MIRAKURUN_UPSTREAM};
        proxy_redirect off;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
