# これはmunin用のリバースプロキシ設定サンプルです。必要に応じて編集してください。
# 認証が必要な場合は、下記のBasic認証の設定を有効にしてください。
server {
    listen       443 ssl; http2 on;
    listen  [::]:443 ssl;
    server_name munin.${DOMAIN};

    ssl_certificate      /etc/letsencrypt/live/munin.${DOMAIN}/fullchain.pem;
    ssl_certificate_key  /etc/letsencrypt/live/munin.${DOMAIN}/privkey.pem;
    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:10m;
    ssl_session_tickets off;

    ssl_protocols TLSv1.3 TLSv1.2;
    ssl_ciphers 'ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES128-GCM-SHA256';
    ssl_prefer_server_ciphers off;

    add_header Strict-Transport-Security "max-age=2592000" always;

    proxy_redirect                          off;
    proxy_set_header Host                   $host;
    proxy_set_header X-Real-IP              $remote_addr;
    proxy_set_header X-Forwarded-Host       $host;
    proxy_set_header X-Forwarded-Server     $host;
    proxy_set_header X-Forwarded-Proto      $scheme;
    proxy_set_header X-Forwarded-For        $proxy_add_x_forwarded_for;
    proxy_set_header Authorization $http_authorization; # 必要な場合は認証ヘッダを転送

    # Basic authentication (fail2ban対応のためproxyで実行)
    auth_basic "Restricted Access";
    auth_basic_user_file /etc/nginx/.htpasswd;  # 必要に応じて設定
        
    location / {
        proxy_pass http://munin.${DOMAIN}/munin/;
    }

    # redirect server error pages to the static page /50x.html
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
