server {
    listen 80;
    listen [::]:80;
    server_name ${TRAEFIK_HOST};

    location ^~ /.well-known/ {
        root /usr/share/nginx/html;
        try_files $uri =404;
    }

    location / {
        root /usr/share/nginx/html;
        index proxy-dashboard/index.html;
        try_files /proxy-dashboard/index.html =404;
    }
}
